version: 2.1

orbs:
  node: circleci/node@5

jobs:
  test-frontend:
    executor: node/default
    working_directory: ~/project/frontend
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run frontend tests
          command: npm test --passWithNoTests
          
  build-frontend:
    executor: node/default
    working_directory: ~/project/frontend
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build frontend
          command: npm run build
      - run:
          name: Create frontend artifacts directory
          command: mkdir -p ~/artifacts/frontend
      - run:
          name: Copy frontend build artifacts
          command: cp -R build ~/artifacts/frontend
      - store_artifacts:
          path: ~/artifacts/frontend
          destination: frontend-build

  test-backend:
    executor: node/default
    working_directory: ~/project/Backend
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run backend tests
          command: npm test --passWithNoTests
          
  build-backend:
    executor: node/default
    working_directory: ~/project/Backend
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Create backend artifacts directory
          command: mkdir -p ~/artifacts/backend
      - run:
          name: Copy backend server file
          command: cp -R server.mjs ~/artifacts/backend  # Adjust this to match your backend entry file
      - store_artifacts:
          path: ~/artifacts/backend
          destination: backend-build

workflows:
  build-and-test:
    jobs:
      - test-frontend
      - build-frontend:
          requires:
            - test-frontend
      - test-backend
      - build-backend:
          requires:
            - test-backend
